---
- name: Master - named.conf
  run_once: true
  template:
    src: "{{ role_path }}/templates/named.conf.master.j2"
    dest: "{{ data_root | mandatory }}/master/named.conf"
    owner: "{{ container_uid | string | mandatory }}"
    group: "{{ container_gid | string | mandatory }}"
    mode: '0640' # The file should be only changed by this role, not by BIND or anyone manually
    force: yes
  notify: restart_master

- name: Master - Forward zone
  run_once: true
  template:
    src: "{{ role_path }}/templates/zone-forward.master.j2"
    dest: "{{ data_root }}/master/forward.zone"
    owner: "{{ container_uid | string | mandatory }}"
    group: "{{ container_gid | string | mandatory }}"
    mode: '0640'
    force: yes
  notify: restart_master

- name: Master - Services reverse zone
  run_once: true
  template:
    src: "{{ role_path }}/templates/zone-reverse.master.j2"
    dest: "{{ data_root }}/master/services-reverse.zone"
    owner: "{{ container_uid | string | mandatory }}"
    group: "{{ container_gid | string | mandatory }}"
    mode: '0640'
    force: yes
  notify: restart_master