- name: Fetch kubernetes version
  uri:
    url: https://dl.k8s.io/release/stable.txt
    return_content: yes
  register: kubectl_version

- name: Fetch kubectl checksum
  uri:
    url: https://dl.k8s.io/{{ kubectl_version.content }}/bin/linux/amd64/kubectl.sha256
    return_content: yes
  register: kubectl_checksum

- name: "Download kubectl"
  get_url:
    url: https://dl.k8s.io/release/{{ kubectl_version.content }}/bin/linux/amd64/kubectl
    checksum: "sha256:{{ kubectl_checksum.content }}"
    dest: /usr/local/bin/kubectl
    mode: 0755
    owner: root
    group: root
