- name: Fetch kubeaudit checksums
  uri:
    url: https://github.com/Shopify/kubeaudit/releases/latest/download/kubeaudit_0.20.0_checksums.txt
    return_content: yes
  register: kubeaudit_checksums

- name: "Download kubeaudit"
  get_url:
    url: https://github.com/Shopify/kubeaudit/releases/latest/download/kubeaudit_0.20.0_linux_amd64.tar.gz
    checksum: "sha256:{{ (kubeaudit_checksums.content | regex_search('(?P<checksum>[a-z0-9]+)\\W*kubeaudit_.*_linux_amd64', '\\g<checksum>', multiline=True)) }}"
    dest: /tmp/kubeaudit.tar.gz
    mode: 0755
    owner: root
    group: root

- name: "Extract archive"
  ansible.builtin.unarchive:
    src: /tmp/kubeaudit.tar.gz
    dest: /usr/local/bin
    extra_opts:
      - "--wildcards"
      - "kubeaudit"
    remote_src: yes

- name: "Rename file to be compatible with kubectl plugin"
  copy:
    src: /usr/local/bin/kubeaudit
    dest: /usr/local/bin/kubectl-audit
    remote_src: yes

- name: "Set file permissions"
  file:
    path: /usr/local/bin/kubectl-audit
    state: file
    mode: 0755
    owner: root
    group: root

- name: "Remote temp files"
  file:
    path: "{{ item }}"
    state: absent
  with_items: 
    - "/tmp/kubeaudit.tar.gz"
    - "/usr/local/bin/kubeaudit"