---
# Workaround: Docker dependencies conflict with podman's dependencies which are installed by default with CentOS
- name: "Uninstall packages conflicting with Docker on CentOS 8"
  package:
    name:
      - podman
      - buildah
    state: absent
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: "Install Docker"
  include_role:
    name: "geerlingguy.docker"
  vars:
    docker_edition: 'ce'
    docker_install_compose: true
    docker_service_state: started
    docker_users:
      - "{{ admin_user }}"

- name: "Install Docker pip module"
  include_role:
    name: geerlingguy.pip
  vars:
    pip_package: python3-pip
    pip_install_packages:
    - name: docker
    - name: jsondiff
    - name: pyyaml

- name: "Set custom Docker group GID"
  group:
    gid: "{{ docker_gid | mandatory }}"
    name: "docker"
  when: docker_gid is defined