lynis_hardening_ignore_list: |
  # Proxmox needs promiscous mode to pass networking to the VMs
  skip-test=NETW-3015
  # IpTables used to redirect port 443 to 8006
  skip-test=FIRE-4512
  # Postfix is used only by Proxmox internally, this check brings no value
  skip-test=MAIL-8818
  # Physical access to the servers is restricted and this would make emergency resolution much more difficult
  skip-test=BOOT-5122
  # Check does not work correctly on Proxmox (see https://github.com/CISOfy/lynis/issues/788)
  skip-test=KRNL-5788
  # Proxmox does not allow user to change the partition layout
  skip-test=FILE-6310
  # Logging to a centralized log host is currently not feasible
  skip-test=LOGG-2154
  # Legal banners are not important in our set up
  skip-test=BANN-7126
  skip-test=BANN-7130
  # USB devices and similar are useful in our usecase
  skip-test=USB-1000
  skip-test=STRG-1846
  # Only one user signs into the machine, accounting is not needed and is not worth the required resources
  skip-test=ACCT-9622
  skip-test=ACCT-9626
  skip-test=ACCT-9628
  # Proxmox leaves locked account for ceph on purpose
  skip-test=AUTH-9284
  # Not worth the effort, the services are installed by default with Proxmox
  skip-test=BOOT-5264
  # Passwords are just a back up and should not be used anyway, expiring passwords puts us in danger or locking ourselves from the server
  skip-test=AUTH-9229