- include_tasks: ../../load-kubeconfig.yml

- name: Create resources
  run_once: true
  k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    definition: "{{ lookup('template', item) }}"
    state: present
    apply: yes
    validate:
      fail_on_error: yes
      strict: yes
  with_items:
    - "service-account.yml.j2"
    - "cluster-role.yml.j2"
    - "cluster-role-binding.yml.j2"
    - "config-map.yml.j2"
    - "deployment.yml.j2"
    - "service-tcp.yml.j2"
    - "service-udp.yml.j2"
    - "network-policy.yml.j2"