- include_tasks: ../../load-kubeconfig.yml

- name: Create resources
  run_once: true
  k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    definition: "{{ lookup('template', item) }}"
    state: present
    apply: yes
    validate:
      fail_on_error: yes
      strict: yes
  with_items:
    - "config-map.yml.j2"
    - "persistent-volume-claim.yml.j2"
    - "deployment.yml.j2"
    - "service-udp.yml.j2"
    
  # Note: there is no traffic policy by design. This is due to the limitation of how UDP broadcast forwarding works (there's no source IP because the client does not have an ip address yet)