---
collections:
- name: oasis_roles.system
- name: community.general
  version: 4.2.0

roles:
- name: geerlingguy.docker
  version: 3.0.0
- name: geerlingguy.pip
- name: geerlingguy.security
- name: geerlingguy.clamav