---
collections:
- name: oasis_roles.system
- name: community.general
  version: 4.2.0
- name: gluster.gluster
  version: 1.0.2

roles:
- name: geerlingguy.docker
  version: 3.0.0
- name: geerlingguy.pip
- name: geerlingguy.security
- name: geerlingguy.clamav
- name: geerlingguy.helm