# opensmtpd_dir
# opensmtpd_network
# opensmtpd_ipv4
# opensmtpd_service_uid
# opensmtpd_service_gid
# opensmtpd_relay_smtp_username
# opensmtpd_relay_smtp_password
# opensmtpd_relay_port
# opensmtpd_relay_host
# opensmtpd_relay_domain
# opensmtpd_relay_anonymous_allowed_cidrs
opensmtpd_service_name: "opensmtpd-relay"
opensmtpd_docker_image_tag: "latest"