---
- name: Add host entries for other nodes (FQDN and hostname)
  lineinfile:
    path: /etc/hosts
    regexp: "^.*\\W+{{ item | replace('.', '\\.') }}\\W+{{ hostvars[item].fqdn | replace('.', '\\.') }}\\W*$"
    line: "{{ hostvars[item]['ansible_host'] }} {{ item }} {{ hostvars[item].fqdn }}"
  with_items: "{{ groups['all'] }}"