- name: Get all service accounts
  register: k3s_service_accounts
  kubernetes.core.k8s_info:
    kubeconfig: "{{ kubeconfig_path }}"
    kind: ServiceAccount


- name: Disable automatic mounting of service account tokens to pods
  run_once: true
  kubernetes.core.k8s_json_patch:
    kubeconfig: "{{ kubeconfig_path }}"
    namespace: "{{ item.metadata.namespace }}"
    name: "{{ item.metadata.name }}"
    kind: ServiceAccount
    patch:
      - op: add
        path: /automountServiceAccountToken
        value: false
  with_items: "{{ k3s_service_accounts.resources }}"