- name: Create metallb namespace
  run_once: true
  k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    definition: "{{ lookup('file', 'metallb-namespace.yml') }}"
    state: present

- name: Add MetalLB helm repo
  kubernetes.core.helm_repository:
    name: metallb
    repo_url: "https://metallb.github.io/metallb"
    state: present

- name: Install MetalLB
  run_once: true
  kubernetes.core.helm:
    state: present
    release_name: metallb
    release_namespace: metallb-system
    create_namespace: no
    chart_version: "{{ k3s_cluster_metallb_chart_version }}"
    chart_ref: metallb/metallb
    kubeconfig_path: "{{ kubeconfig_path }}"
    values:
      prometheus:
        scrapeAnnotations: true
      controller:
        resources:
          requests:
            cpu: "{{ k3s_cluster_metallb_controller_cpu_request }}"
            memory: "{{ k3s_cluster_metallb_controller_memory_request }}"
          limits:
            cpu: "{{ k3s_cluster_metallb_controller_cpu_request }}"
            memory: "{{ k3s_cluster_metallb_controller_memory_limit }}"
      speaker:
        resources:
          requests:
            cpu: "{{ k3s_cluster_metallb_speaker_cpu_request }}"
            memory: "{{ k3s_cluster_metallb_speaker_memory_request }}"
          limits:
            cpu: "{{ k3s_cluster_metallb_speaker_cpu_request }}"
            memory: "{{ k3s_cluster_metallb_speaker_memory_limit }}"

- name: Set up MetalLB address pool
  run_once: true
  k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    definition: "{{ lookup('template', 'metallb-pools.yml.j2') }}"
    state: present