- include_tasks: ../../load-kubeconfig.yml

- name: Create resources
  run_once: true
  k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    definition: "{{ lookup('template', item) }}"
    state: present
    apply: yes
    validate:
      fail_on_error: yes
      strict: yes
  with_items:
    - "job.yml.j2"