- include_tasks: ../../shared/apt.yml
- include_tasks: hosts.yml
- include_tasks: install.yml

- include_tasks: ../../shared/tls.yml
  register: gluster_tls
  vars:
    gluster_node_hostname: "{{ ansible_hostname }}" # Servers must use their gluster specific identity
    gluster_node_additional_names: 
    - "{{ fqdn }}"

- include_tasks: ../../shared/volume-mount.yml
  vars:
    gluster_mount_config: "{{ item }}"
  when: gluster_volume_mounts is defined
  with_items: "{{ gluster_volume_mounts }}"