- include_tasks: ../../load-kubeconfig.yml

- name: Create resources
  run_once: true
  k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    definition: "{{ lookup('template', item) }}"
    state: present
    apply: yes
    validate:
      fail_on_error: yes
      strict: yes
  with_items:
    - "service-account.yml.j2"
    - "cluster-role.yml.j2"
    - "cluster-role-binding.yml.j2"

- name: Generate run id
  set_fact:
    kube_audit_run_id: "{{ lookup('community.general.random_string', upper=true, lower=true, special=false, numbers=false) }}"

- name: Remove previous runs
  run_once: true
  k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    definition: "{{ lookup('template', 'job.yml.j2') }}"
    state: absent

- name: Re-create job
  run_once: true
  k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    definition: "{{ lookup('template', 'job.yml.j2') }}"
    state: present
    validate:
      fail_on_error: yes
      strict: yes

- name: Get pod logs
  run_once: true
  kubernetes.core.k8s_log:
    kubeconfig: "{{ kubeconfig_path }}"
    namespace: "{{ k3s_namespace }}"
    label_selectors:
    - app.kubernetes.io/name=kube-audit
    - "homecentr.io/run-id={{ kube_audit_run_id }}"
  register: kube_audit_log

- name: Check kube-audit log for errors
  run_once: true
  ansible.builtin.assert:
    that:
      - kube_audit_log is not search("error")
    quiet: true