---
- name: "Master - Create config directory"
  run_once: true
  file:
    path: "{{ data_root }}/master"
    state: directory
    owner: "{{ container_uid | string | mandatory }}"
    group: "{{ container_gid | string | mandatory }}"
    mode: '0750'

- name: "Slave - Create slave config directory"
  run_once: true
  file:
    path: "{{ data_root }}/slave"
    state: directory
    owner: "{{ container_uid | string | mandatory }}"
    group: "{{ container_gid | string | mandatory }}"
    mode: '0750'  