- include_tasks: ../load-kubeconfig.yml

- name: Add jetstack helm repo
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: "https://charts.jetstack.io"
    state: present

- name: Deploy cert-manager
  run_once: true
  kubernetes.core.helm:
    state: present
    release_name: cert-manager
    release_namespace: cert-manager
    create_namespace: yes
    chart_version: "{{ certmanager_chart_version }}"
    chart_ref: jetstack/cert-manager
    kubeconfig_path: "{{ kubeconfig_path }}"
    values:
      installCRDs: true

- name: Create Cloudflare API token secret
  run_once: true
  k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    definition: "{{ lookup('template', 'cloudflare-secret.yml.j2') }}"
    state: present

- name: Create Cloudflare dns based issuer
  run_once: true
  k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    definition: "{{ lookup('template', 'cloudflare-issuer.yml.j2') }}"
    state: present

- name: Create certificates
  run_once: true
  k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    definition: "{{ lookup('template', 'certificate.yml.j2',template_vars=(item | combine({'k3s_namespace': k3s_namespace }))) }}"
    state: present
  with_items: "{{ certmanager_certificates }}"
