- name: "Load fuse kernel module if not present"
  community.general.modprobe:
    name: fuse
    state: present

- name: Create mount directory
  file:
    path: "/mnt/gfs/{{ gluster_volume_name }}"
    state: directory

- name: Mount volume
  ansible.posix.mount:
    path: "/mnt/gfs/{{ gluster_volume_name }}"
    src: "{{ gluster_hostname }}:/{{ gluster_volume_name }}"
    fstype: glusterfs
    opts: defaults,_netdev
    state: mounted