external_dns_ipv4_address: 10.1.2.128 # TBA Secondary address (?)
external_dns_cluster_domain: homecentr.io

external_dns_forwarders_tls_name: dns.google
external_dns_forwarders:
  - 8.8.8.8
  - 8.8.4.4

external_dns_records:
  - name: pve
    type: A
    targets:
      - host: pve1
      - host: pve2
  - name: print
    type: A
    targets:
      - value: 10.1.3.5
  - name: vpn
    type: A
    targets:
      - value: 89.239.25.20

external_dns_known_hosts:
  - name: pve1
    hostname_variable: fqdn
  - name: pve2
    hostname_variable: fqdn
  - name: minion
    hostname_variable: fqdn
  - name: kube1
    hostname_variable: fqdn
  - name: kube2
    hostname_variable: fqdn