---
- name: "Create certbot directory ({{ certbot_root_dir }})"
  file:
    path: "{{ certbot_root_dir }}"
    state: directory
    owner: "{{ certbot_user_id | string }}"
    group: "{{ certbot_group_id | string }}"
    mode: '0750'

- name: "Create certbot directory ({{ certbot_root_dir }}/{{ item }})"
  with_items:
    - state
    - logs
    - secrets
  file:
    path: "{{ certbot_root_dir }}/{{ item }}"
    state: directory
    owner: "{{ certbot_user_id | string }}"
    group: "{{ certbot_group_id | string }}"
    mode: '0750'

# Directory is readable by the group so that other services can use the certificates
- name: "Create ssl certificates directory ({{ certbot_root_dir }}/ssl)"
  file:
    path: "{{ certbot_root_dir }}/certs"
    state: directory
    owner: "{{ certbot_user_id | string }}"
    group: "{{ certbot_cert_readers_group_name }}"
    mode: '0740'
