---
- import_tasks: ../../shared/docker-service-iam.yml
- import_tasks: ../../shared/docker-service-dir.yml
  vars:
    service_name: "certbot"

- name: Create 'ssl' directory
  run_once: true
  file:
    path: "{{ homecentr_root | mandatory }}/ssl"
    state: directory
    owner: "{{ container_uid | string }}"
    group: "swarm-services"
    mode: '0740'

- name: "Create cloudflare credential file"
  run_once: true
  template:
    src: cloudflare.ini.j2
    dest: "{{ homecentr_root | mandatory }}/certbot/cloudflare.ini"
    owner: "{{ container_uid | mandatory | string }}"
    group: "{{ container_gid | mandatory | string }}"
    mode: '0600'

- name: "Certbot docker stack"
  run_once: true
  docker_stack:
    prune: yes
    name: homecentr-certbot
    compose:
      - "{{ lookup('template', 'docker-compose.yml.j2') | from_yaml }}"

- name: "Wait for certificate to be issued (fullchain.pem)"
  wait_for:
    path: "{{ homecentr_root }}/ssl/live/{{ root_domain }}/fullchain.pem"
    state: present
    timeout: 120

- name: "Wait for certificate to be issued (cert.pem)"
  wait_for:
    path: "{{ homecentr_root }}/ssl/live/{{ root_domain }}/cert.pem"
    state: present
    timeout: 120

- name: "Wait for certificate to be issued (privkey.pem)"
  wait_for:
    path: "{{ homecentr_root }}/ssl/live/{{ root_domain }}/privkey.pem"
    state: present
    timeout: 120