- name: "Install Network UPS Tools"
  package:
    name: nut
    state: present

- name: "Check if node is hosting a ups device"
  set_fact:
    hosted_ups_devices: "{{ ups_devices | selectattr('monitored_by', 'equalto', inventory_hostname) | map(attribute='name')  }}"

- include_tasks: master.yml
  when: (hosted_ups_devices | length) > 0

- name: "Configure UPS Monitor mode"
  notify: restart ups_monitor
  copy:
    dest: /etc/nut/nut.conf
    force: yes
    mode: 0640
    owner: root
    group: nut
    content: |
      MODE={{ 'netserver' if (hosted_ups_devices | length) > 0 else 'netclient' }}

- name: "Configure Network UPS Tools Monitor"
  notify: restart ups_monitor
  copy:
    dest: /etc/nut/upsmon.conf
    force: yes
    mode: 0640
    owner: root
    group: nut
    content: "{{ lookup('template', 'upsmon.conf.j2') }}"

- name: "Start the ups monitor"
  service:
    name: nut-monitor
    state: started