---
- name: "Initialize cluster"
  docker_swarm:
    state: present
    advertise_addr: "{{ ansible_default_ipv4.address }}"
  when: inventory_hostname == play_hosts[0]
  register: swarm_info

- name: "Join cluster"
  docker_swarm:
    state: join
    advertise_addr: "{{ inventory_hostname }}"
    remote_addrs: "{{ play_hosts[0] }}"
    join_token: "{{ hostvars[swarm_init_node_name].swarm_info.swarm_facts.JoinTokens.Manager }}"
  when: inventory_hostname != play_hosts[0]

- name: "Set node labels"
  docker_node:
    hostname: "{{ hostname }}"
    labels: "{{ docker_node_labels }}"
  when: docker_node_labels is defined