---
- name: "Create user {{ user_name | mandatory }}"
  ansible.builtin.user:
    name: "{{ user_name | mandatory }}"
    shell: /bin/bash
    state: present

- name: "Download public keys from GitHub"
  uri:
    url: "https://github.com/{{ github_user_name | default(user_name) }}.keys"
    return_content: yes
  register: public_keys

- name: Set authorized key
  authorized_key:
    user: "{{ user_name | mandatory }}"
    state: present
    key: "{{ public_keys['content'] }}"