- name: "Create user and group"
  import_tasks: "../../common/service-iam.yml"
  vars:
    service_name: "{{ opensmtpd_relay_service_name }}"
    service_gid: "{{ opensmtpd_relay_service_uid }}"

- name: "Create opensmtpd root directory"
  file:
    path: "{{ opensmtpd_relay_dir }}"
    state: directory
    owner: "{{ opensmtpd_relay_service_uid }}"
    group: "{{ opensmtpd_relay_service_uid }}"
    mode: 0640

- name: "Create configuration file"
  template:
    src: "opensmtpd.conf.j2"
    dest: "{{ opensmtpd_relay_dir }}/smtpd.conf"
    owner: "{{ opensmtpd_relay_service_uid }}"
    group: "{{ opensmtpd_relay_service_uid }}"
    mode: 0440
  notify: restart_opensmtpd

- name: "Deploy docker compose (local only, should not directly depend on swarm)"
  docker_compose:
    state: present
    project_name: "homecentr-{{ opensmtpd_relay_service_name }}"
    definition:
      version: '3.9'
      services:
        opensmtpd:
          image: "ghcr.io/homecentr/opensmtpd:{{ opensmtpd_relay_docker_image_tag }}"
          environment:
            PUID: "{{ opensmtpd_relay_service_uid }}"
            PGID: "{{ opensmtpd_relay_service_gid }}"
          volumes:
            - "{{ opensmtpd_relay_dir }}:/config:ro"
          ports:
            - "25:25/tcp"
          networks:
            homecentr_services:
              ipv4_address: "{{ opensmtpd_relay_ipv4_address }}"
      networks:
        homecentr_services:
          name: "{{ opensmtpd_relay_network }}"
          external: true