---
- name: "Create local non-root ssh user"
  tags:
    - ssh
  include_role:
    name: "./roles/utils/ssh-user"
  vars:
    user_name: "{{ admin_user }}"

- name: "SSH hardening"
  import_role:
    name: geerlingguy.security
  tags:
    - ssh
  vars:
    security_ssh_password_authentication: "no"
    security_ssh_permit_root_login: "no"
    security_ssh_usedns: "no"
    security_ssh_permit_empty_password: "no"
    security_ssh_challenge_response_auth: "no"
    security_ssh_gss_api_authentication: "no"
    security_ssh_x11_forwarding: "no"
    security_sudoers_passwordless:
    - "{{ admin_user }}"