---
all:
  children:
    proxmox_nodes:
      hosts:
        pve1:
        pve2:
    proxmox_quorum_devices:
      hosts:
        minion:
    swarm_nodes:
      hosts:
        swarm1:
        swarm2:
        minion:
    smtp_relays:
      hosts:
        minion:
    ups_masters:
      hosts:
        minion:
    ups_slaves:
      hosts:
        pve1:
        pve2:
        swarm1:
        swarm2:
    glusterfs_nodes:
      hosts:
        pve1:
        pve2:
        minion: