---
all:
  children:
    proxmox_nodes:
      hosts:
        pve1:
        pve2:
    proxmox_quorum_devices:
      hosts:
        buttler:
    swarm_managers:
      hosts:
        # swarm1:
        # swarm2:
        buttler:
    smtp_relays:
      hosts:
        buttler:
    ups_masters:
      hosts:
        buttler:
    ups_slaves:
      hosts:
        pve1:
        pve2:
    x86_64_nodes:
      hosts:
        pve1:
        pve2: