---
all:
  children:
    pve_nodes:
      hosts:
        pve1:
        pve2:
        pve3:
    k3s_nodes:
      hosts:
        kube1:
        kube2:
        kube3:
    ups_masters:
      hosts:
        pve3:
    ups_slaves:
      hosts:
        pve1:
        pve2:
    gluster_nodes:
      children:
        gluster_servers:
          hosts:
            pve1:
            pve2:
            pve3:
        gluster_clients:
          hosts:
            pve1:
            pve2:
            pve3:
            kube1:
            kube2:
            kube3: