---
all:
  children:
    proxmox_nodes:
      hosts:
        pve1:
        pve2:
    proxmox_quorum_devices:
      hosts:
        minion:
    k3s_nodes:
      hosts:
        kube1:
        kube2:
        minion:
    ups_masters:
      hosts:
        minion:
    ups_slaves:
      hosts:
        pve1:
        pve2:
        kube1:
        kube2:
    glusterfs_nodes:
      hosts:
        pve1:
        pve2:
        minion: