---
all:
  children:
    pve_nodes:
      hosts:
        pve1:
        pve2:
    pve_qdevices:
      hosts:
        minion:
    k3s_nodes:
      hosts:
        kube1:
        kube2:
        # minion:
    ups_masters:
      hosts:
        minion:
    ups_slaves:
      hosts:
        pve1:
        pve2:
        kube1:
        kube2:
    gluster_nodes:
      hosts:
        pve1:
        pve2:
        minion: