- include_tasks: ../../load-kubeconfig.yml

- name: Create resources
  run_once: true
  k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    definition: "{{ lookup('template', item) }}"
    state: present
    apply: yes
    validate:
      fail_on_error: yes
      strict: yes
  with_items:
    - "persistent-volume-claim.yml.j2"
    - "deployment.yml.j2"
    - "service.yml.j2"
    - "ingress-http.yml.j2"
    - "ingress-https.yml.j2"
    - "ingress-fwdauth.yml.j2"
    - "network-policy.yml.j2"