ansible_host: 10.1.2.30
fqdn: minion.homecentr.io
ups_name: eaton1
ups_shutdown_delay_seconds: 300 # Wait 5 minutes before shutting down to give other machines time to recognize they need to shut down

ssh_allow_root_login_trusted_clients:
- pve1
- pve2

gluster_ip: 10.1.2.30
gluster_hostname: gfs-minion
gluster_fqdn: gfs-minion.homecentr.io
gluster_has_direct_connection: no

k3s_extra_server_args: "--bind-address 10.1.2.30 --node-ip 10.1.2.30"
k3s_cluster_join: https://kube1:6443
k3s_labels:
  "allow-workload": "false"
  "allow-vital-workload": "true"
  "gpu-acceleration": "true"