---
all:
  children:
    k3s_nodes:
      hosts:
        node1:
        node2:
        node3:
    pve_nodes:
    pve_qdevices:
    gluster_nodes:
      hosts:
        node1:
        node2:
        node3:
    gluster_arbiter_nodes:
      hosts:
        node3:
    gluster_storage_nodes:
      hosts:
        node1:
        node2: