- include_tasks: ../load-kubeconfig.yml

- name: Add authentik helm repo
  kubernetes.core.helm_repository:
    name: authentik
    repo_url: https://charts.goauthentik.io
    state: present

- name: Create custom resources
  run_once: true
  k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    definition: "{{ lookup('template', item) }}"
    state: present
    apply: yes
    validate:
      fail_on_error: yes
      strict: yes
  with_items:
    - "traefik-middleware.yml.j2"
    - "ingress-http.yml.j2"
    - "ingress-https.yml.j2"
    - "pvc-branding.yml.j2"

- name: Create branding config map
  run_once: true
  k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    definition: "{{ lookup('template', 'config-map-branding.yml.j2') }}"
    state: present
    apply: no # Must be set to no otherwise the k8s ansible module adds the whole config map content to annotations which breaches the limit
    force: yes # To replace the config map since apply cannot be enabled
    validate:
      fail_on_error: yes
      strict: yes

- name: Debug branding
  delegate_to: localhost
  become: false
  copy:
    dest: /mnt/d/Temp/test.jpg
    content: "{{ lookup('url', authentik_login_background_url, split_lines=False) }}"

# Note: the helm chart has a built-in prometheus configuration which can be used an inspiration for the other services
- name: Deploy Authentik
  run_once: true
  kubernetes.core.helm:
    state: present
    release_name: authentik
    release_namespace: "{{ k3s_namespace }}"
    create_namespace: no
    chart_version: "{{ authentik_chart_version }}"
    chart_ref: authentik/authentik
    kubeconfig_path: "{{ kubeconfig_path }}"
    values:
      volumeMounts:
        - name: branding-config
          mountPath: /web/dist/login-background.jpg
          subPath: loginBackground
          readOnly: true
        - name: branding-config
          mountPath: /web/dist/custom.css
          subPath: customStyles
          readOnly: true
        - name: branding-config
          mountPath: /web/dist/favicon.ico
          subPath: favicon
          readOnly: true
        - name: branding-config
          mountPath: /web/dist/logo.png
          subPath: logo
          readOnly: true
      volumes:
        - name: branding-config
          configMap:
            name: authentik-branding
      image:
        tag: "{{ authentik_image_tag }}"
      ingress:
        enabled: false
      authentik:
        secret_key: "{{ authentik_cookie_signing_key }}"
        postgresql:
          password: "{{ authentik_database_password }}"
        email:
          from: "{{ authentik_email_from }}"
          host: "{{ authentik_email_smtp_host }}"
          port: "{{ authentik_email_smtp_port }}"
          use_ssl: "{{ 'yes' if authentik_email_smtp_protocol == 'ssl' else 'no' }}"
          use_tls: "{{ 'yes' if authentik_email_smtp_protocol == 'tls' else 'no' }}"
          username: "{{ authentik_email_smtp_username }}"
          password: "{{ authentik_email_smtp_password }}"
      error_reporting:
        enabled: false
      postgresql:
        enabled: true
        postgresqlPassword: "{{ authentik_database_password }}"
        persistence:
          enabled: true
          storageClass: "{{ authentik_storage_class }}"
          accessModes:
            - ReadWriteOnce
      redis:
        enabled: true
        architecture: standalone