- include_tasks: ../load-kubeconfig.yml

- name: Add authentik helm repo
  kubernetes.core.helm_repository:
    name: authentik
    repo_url: https://charts.goauthentik.io
    state: present


# Note: the helm chart has a built-in prometheus configuration which can be used an inspiration for the other services

# TODO: Define http ingress with redirect to https
# TODO: Define https ingress

- name: Deploy Authentik
  run_once: true
  kubernetes.core.helm:
    state: present
    release_name: authentik
    release_namespace: "{{ authentik_target_namespace }}"
    create_namespace: no
    chart_version: "{{ authentik_chart_version }}"
    chart_ref: authentik/authentik
    kubeconfig_path: "{{ kubeconfig_path }}"
    values:
      image:
        tag: "{{ authentik_image_tag }}"
      ingress:
        enabled: false
      authentik:
        secret_key: "{{ authentik_cookie_signing_key }}"
        postgresql:
          password: "{{ authentik_database_password }}"
        # TODO: Configure SMTP
      postgresql:
        enabled: true
        postgresqlPassword: "{{ authentik_database_password }}"
        persistence:
          enabled: true
          storageClass: "{{ authentik_database_storage_class }}"
          accessModes:
            - ReadWriteOnce
      redis:
        enabled: true
        architecture: standalone

- name: Create custom resources
  run_once: true
  k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    definition: "{{ lookup('template', item) }}"
    state: present
    apply: yes
    validate:
      fail_on_error: yes
      strict: yes
  with_items:
    - "traefik-redirect-to-https-middleware.yml.j2"
    - "ingress-http.yml.j2"
    - "ingress-https.yml.j2"