- include_tasks: ../load-kubeconfig.yml

- include_tasks: ../shared/gfs-storage.yml
  vars:
    gfs_storage_gluster_volume: k3s-services
    gfs_storage_namespace: monitoring
    gfs_storage_service_name: prometheus
    gfs_storage_directory_name: data
    gfs_storage_service_instance_name: prometheus
    gfs_storage_size_gigabytes: 10
    gfs_storage_create_pvc: no

- name: Add prometheus-community helm repo
  kubernetes.core.helm_repository:
    name: prometheus-community
    repo_url: https://prometheus-community.github.io/helm-charts
    state: present

- name: Deploy Prometheus Operator
  run_once: true
  kubernetes.core.helm:
    state: present
    release_name: prometheus-operator
    release_namespace: "{{ prometheus_operator_namespace }}"
    create_namespace: no
    chart_version: "{{ prometheus_operator_chart_version }}"
    chart_ref: prometheus-community/kube-prometheus-stack
    kubeconfig_path: "{{ kubeconfig_path }}"
    values:
      namespaceOverride: "{{ prometheus_operator_namespace }}"
      nodeExporter:
        enabled: false # node-exporter deployed manually to all nodes (not just kube nodes)
      
# TODO: Define Prometheus instance via CRD and link it to the storage