---
# Validation
- name: "Validate variables"
  fail:
    msg: "Required variable {{item}} has not been provided"
  when: vars[item] is undefined
  loop:
    - auth_docker_image_version
    - auth_group_id
    - auth_group_name
    - auth_user_id
    - auth_user_name
    - auth_domain
    - auth_root_dir
    - auth_cookie_secret
    - auth_signing_key
    - auth_idp_type
    - auth_idp_url
    - auth_idp_client_id
    - auth_idp_client_secret

- name: Create auth directory
  run_once: true
  file:
    path: "{{ auth_root_dir }}"
    state: directory
    owner: "{{ auth_user_id | string }}"
    group: "{{ auth_group_id | string }}"
    mode: 0750

- name: Pomerium config
  template:
    src: 'config.yml.j2'
    dest: "{{ auth_root_dir }}/config.yml"
    owner: "{{ auth_user_id | string }}"
    group: "{{ auth_group_id | string }}"
    force: yes
    mode: 0440

# Docker
- name: Docker stack
  run_once: true
  docker_stack:
    prune: yes
    name: homecentr-auth
    compose:
      - "{{ lookup('template', 'docker-compose.yml.j2') | from_yaml }}"