---
# Validation
- name: "Validate variables"
  fail:
    msg: "Required variable {{item}} has not been provided"
  when: vars[item] is undefined
  loop:
    - ingress_certificates_group_id
    - ingress_certificates_dir
    - ingress_docker_image_version
    - ingress_group_id
    - ingress_group_name
    - ingress_user_uid
    - ingress_user_name
    - ingress_log_level
    - ingress_root_dir
    - ingress_dashboard_domain

# IAM
- name: "Create group '{{ ingress_group_name }}'"
  group:
    name: "{{ ingress_group_name }}"
    gid: "{{ ingress_group_id }}"
    state: present

- name: "Create user '{{ ingress_user_name }}'"
  user:
    name: "{{ ingress_user_name }}"
    uid: "{{ ingress_user_id }}"
    group: "{{ ingress_group_name }}"
    state: present

- name: Create ingress root directory
  run_once: true
  file:
    path: "{{ ingress_root_dir }}"
    state: directory
    owner: "{{ ingress_user_id | string }}"
    group: "{{ ingress_group_id | string }}"
    mode: 0750

# Configuration files
- name: Traefik static config
  template:
    src: 'static.yml.j2'
    dest: "{{ ingress_root_dir }}/traefik.yml"
    owner: "{{ ingress_user_id | string }}"
    group: "{{ ingress_group_id | string }}"
    force: yes
    mode: 0440

- name: Traefik dynamic config
  template:
    src: 'dynamic.yml.j2'
    dest: "{{ ingress_root_dir }}/dynamic.yml"
    owner: "{{ ingress_user_id | string }}"
    group: "{{ ingress_group_id | string }}"
    force: yes
    mode: 0440

# Docker
- name: Docker stack
  run_once: true
  docker_stack:
    prune: yes
    name: homecentr-ingress
    compose:
      - "{{ lookup('template', 'docker-compose.yml.j2') | from_yaml }}"