---
- import_tasks: ../../shared/docker-service-iam.yml
- import_tasks: ../../shared/docker-service-docker-socket-iam.yml

- name: Traefik stack
  run_once: true
  docker_stack:
    prune: yes
    name: homecentr-traefik
    compose:
      - "{{ lookup('template', 'docker-compose.yml.j2') | from_yaml }}"