- name: Download Kadalu CLI
  get_url:
    url: "https://github.com/kadalu/kadalu/releases/download/{{ k3s_kadalu_version }}/kubectl-kadalu"
    dest: /usr/bin/kubectl-kadalu
    mode: 0711
    owner: root
    group: root

- name: Deploy Kadalu operator
  run_once: true
  k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    definition: "{{ lookup('file', 'kadalu-operator.yml') }}"
    state: present
    validate:
      fail_on_error: yes
      strict: yes


- name: Deploy Kadalu CSI plugin
  run_once: true
  k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    definition: "{{ lookup('file', 'kadalu-csi-plugin.yml') }}"
    state: present
    validate:
      fail_on_error: yes
      strict: yes