- name: "Define Persistent volume claims for non-native volumes"
  run_once: true
  k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    definition: "{{ lookup('template', 'persistent-volume-claim.yml.j2', template_vars=item) }}"
    state: present
    validate:
      fail_on_error: yes
      strict: yes
  with_items: "{{ kadalu_gluster_volumes  | selectattr('mode', 'equalto', 'pv_direct') }}"