---
- name: "Create group '{{ group_name }}'"
  group:
    name: "{{ group_name }}"
    gid: "{{ container_gid | mandatory }}"
    state: present

- name: "Create user '{{ user_name }}'"
  user:
    name: "{{ user_name }}"
    uid: "{{ container_uid | mandatory }}"
    group: "{{ group_name }}"
    groups:
      - "{{ group_name }}"
    state: present

- name: "Add user '{{ user_name }}' to Docker group"
  user:
    name: "{{ user_name }}"
    append: true
    groups:
      - docker

- name: "Add '{{ admin_user }}' to the group '{{ group_name }}'"
  user:
    name: "{{ admin_user }}"
    append: true
    groups:
      - "{{ group_name }}"
  when: admin_user is defined