---
- name: "Validate variables"
  fail:
    msg: "Required variable {{item}} has not been provided"
  when: vars[item] is undefined
  loop:
    - network_connector_docker_image_version
    - network_connector_group_id
    - network_connector_group_name
    - network_connector_user_id
    - network_connector_user_name

- name: "Create group '{{ network_connector_group_name }}'"
  group:
    name: "{{ network_connector_group_name }}"
    gid: "{{ network_connector_group_id }}"
    state: present

- name: "Create user '{{ network_connector_user_name }}'"
  user:
    name: "{{ network_connector_user_name }}"
    uid: "{{ network_connector_user_id }}"
    group: "{{ network_connector_group_name }}"
    state: present

- name: Network Connector stack
  run_once: true
  docker_stack:
    prune: yes
    name: homecentr-network-connector
    compose:
      - "{{ lookup('template', 'docker-compose.yml.j2') | from_yaml }}"