- name: Get Debian version ID
  shell: grep 'VERSION_ID=' /etc/os-release | cut -d '=' -f 2 | tr -d '"'
  register: debid

- name: Get Debian version
  shell: "grep 'VERSION=' /etc/os-release | grep -Eo '[a-z]+'"
  register: debver

- name: Get architecture
  shell: "dpkg --print-architecture"
  register: debarch

- name: Add GlusterFS apt repository key
  ansible.builtin.apt_key:
    url: https://download.gluster.org/pub/gluster/glusterfs/{{ gluster_major_version }}/rsa.pub
    state: present

- name: Add Gluster repository into sources
  ansible.builtin.apt_repository:
    repo: deb https://download.gluster.org/pub/gluster/glusterfs/{{ gluster_major_version }}/{{ gluster_major_version }}.{{ gluster_minor_version }}/Debian/{{ debid.stdout | trim }}/{{ debarch.stdout | trim }}/apt {{ debver.stdout | trim }} main
    state: present