- include_tasks: apt.yml
- include_tasks: hosts.yml

- include_tasks: client.yml

- include_tasks: server.yml
  when: "'gluster_servers' in group_names"

- include_tasks: tls.yml

- include_tasks: volume-create.yml
  vars:
    gluster_volume_config: "{{ item }}"
  when: "'gluster_servers' in group_names"
  with_items: "{{ gluster_volumes }}"

- include_tasks: volume-mount.yml
  vars:
    gluster_mount_config: "{{ item }}"
  when: gluster_volume_mounts is defined
  with_items: "{{ gluster_volume_mounts }}"