- name: Create mount directory
  file:
    path: "{{ gluster_mount_config.path }}"
    state: directory

- name: Mount volume
  ansible.posix.mount:
    path: "{{ gluster_mount_config.path }}"
    src: "{{ hostvars[gluster_mount_host].gluster_hostname }}:/{{ gluster_mount_config.name }}"
    fstype: glusterfs
    opts: defaults,_netdev
    state: mounted