---
- name: "Manage non-root admin user"
  hosts: all
  become: true
  become_method: sudo
  tasks:
  - name: Enable passwordless sudo for members of sudo group
    lineinfile:
      path: /etc/sudoers
      state: present
      regexp: '^%sudo'
      line: '%sudo ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'

  - name: "Create admin user '{{ admin_user | mandatory }}' if it doesn't exist"
    ansible.builtin.user:
      name: "{{ admin_user | mandatory }}"
      shell: /bin/bash
      groups:
      - sudo
      state: present

  - name: Set admin user SSH keys
    authorized_key:
      user: "{{ admin_user | mandatory }}"
      state: present
      key: "{{ item }}"
    with_items: "{{ admin_user_ssh_keys }}"

  - name: Set admin user password
    ansible.builtin.user:
      password: "{{ secret_admin_user_password | mandatory | password_hash('sha512', secret_admin_user_password_salt) }}"
      name: "{{ admin_user | mandatory }}"
      shell: /bin/bash
      groups:
      - sudo
      state: present

- name: "Manage root user"
  hosts: all
  become: true
  become_method: sudo
  tasks:
    - name: "Set root user's password"
      ansible.builtin.user:
        name: root
        password: "{{ secret_root_user_password | mandatory | password_hash('sha512', secret_root_user_password_salt) }}"
