---
- name: "Chrony set up"
  hosts: all
  become: true
  become_method: sudo
  tasks:
  - name: "Set up ntp/chrony"
    import_role:
      name: oasis_roles.system.chrony

  - name: "Force chrony to sync time immediately"
    command: chronyc makestep