---
- name: "Install and configure glusterfs"
  hosts: gluster_nodes
  become: true
  become_method: sudo
  tasks:
  - include_role: name=../roles/gluster/cluster

  - name: "Service data volume"
    include_role: name=../roles/gluster/volumes

  # TODO: User data volumes
  # - they end up on the same hdd(s) but contain different data, this will then give an option to move the data to different disks if/when needed.
  # - personal data can also have higher replicas (e.g. three with a brick on each physical disk)
  # videos
  # photos
  # personal
  # cctv
  # images
  # gitpod (?)