---
- name: "Host table entries"
  hosts: all
  become: true
  become_method: sudo
  tasks:
  - name: Add host entries for other nodes (with and without domain)
    lineinfile:
      path: /etc/hosts
      regexp: "^.*\\W+{{ item | replace('.', '\\.') }}\\W+{{ item | replace('.', '\\.') }}\\.{{ server_nodes_domain | replace('.', '\\.') }}\\W*$"
      line: "{{ hostvars[item]['ansible_host'] }} {{ item }} {{ item }}.{{ server_nodes_domain }}"
    with_items: "{{ groups['all'] }}"