---
- name: "Host table entries"
  hosts: all
  become: true
  become_method: sudo
  tasks:
  - name: Add host entries for other nodes (without domain)
    lineinfile:
      path: /etc/hosts
      regexp: "^.*\\W+{{ item | replace('.', '\\.') }}\\W*$"
      line: "{{ hostvars[item]['ansible_host'] }} {{ item }}"
    with_items: "{{ groups['all'] | difference([inventory_hostname]) }}"

  - name: Add host entries for other nodes (with domain)
    lineinfile:
      path: /etc/hosts
      regexp: "^.*\\W+{{ item | replace('.', '\\.') }}\\.{{ server_nodes_domain | replace('.', '\\.') }}\\W*$"
      line: "{{ hostvars[item]['ansible_host'] }} {{ item }}.{{ server_nodes_domain }}"
    with_items: "{{ groups['all'] | difference([inventory_hostname]) }}"

  - name: Add host entry for self (with domain)
    lineinfile:
      path: /etc/hosts
      regexp: "^.*\\W+{{ inventory_hostname | replace('.', '\\.') }}\\.{{ server_nodes_domain | replace('.', '\\.') }}\\W*$"
      line: "127.0.1.1 {{ inventory_hostname }}.{{ server_nodes_domain }}"

