---
- name: "K3s cluster setup"
  hosts: k3s_nodes
  become: true
  become_method: sudo
  tasks:
    - include_role: name=geerlingguy.helm
    
    - include_role: name=../roles/k3s/node
    - include_role: name=../roles/k3s/metal-lb
    