---
- name: "K3s cluster setup"
  hosts: k3s_nodes
  become: true
  become_method: sudo
  tasks:
    - import_role: name=../roles/k3s/cluster
      tags:
        - cluster

    - import_role: name=../roles/k3s/kadalu
      tags:
        - kadalu

    - import_role: name=../roles/k3s/external-dns
      tags:
        - dns

    - import_role: name=../roles/k3s/cert-manager
      tags:
        - cert-manager

    # Deployed in original version
    # TODO: Placement constraints and QoS, SMTP relay should be able to run anywhere and should always run
    # TODO: Reconfigure CoreDNS to use gateway (?)
    # TODO: Configure CoreDNS rewrite to rewrite *.homecentr.io to *.<namespace>.<cluster> or whatever resolves to the static ip
    - import_role: name=../roles/k3s/smtp-relay
      tags:
        - smtp-relay

    - import_role: name=../roles/k3s/unifi-controller
      tags:
        - unifi-controller

    - import_role: name=../roles/k3s/authentik
      tags:
        - authentik
        
    - import_role: name=../roles/k3s/qbittorrent
      tags:
        - qbittorrent


    # TODO: Netboot.xyz
    # TODO: Images samba share (both in one role)

    # TODO: DHCP configured for netboot.xyz

    # TODO: SMB Share - media
    # TODO: SMB Share - private per user data

    # TODO: NextCloud

    # TODO: Torrent client
    # TODO: SMB Share - downloads
    # TODO: Plex

    # TODO: Snipe IT (with database)

    # TODO: Organizr

    # TODO: Radius for VPN (?)


  # - import_role: name=../roles/k3s/dashboard
  #   tags:
  #     - dashboard
  # TODO: Ingress through traefik at k8s.<domain>
  # TODO: Authentication
  # TODO: Switch for standard K8S dashboard
  # TODO: Pass token as header so it doesn't have be entered through UI