---
- name: "K3s cluster setup"
  hosts: k3s_nodes
  become: true
  become_method: sudo
  tasks:
    - import_role: name=../roles/k3s/cluster
      tags:
        - cluster

    - import_role: name=../roles/k3s/kadalu
      tags:
        - kadalu

    - import_role: name=../roles/k3s/external-dns
      tags:
        - dns
        - external-dns

    - import_role: name=../roles/k3s/cert-manager
      tags:
        - cert-manager

    - import_role: name=../roles/k3s/smtp-relay
      tags:
        - smtp-relay
        - smtp

    - import_role: name=../roles/k3s/unifi-controller
      tags:
        - unifi-controller
        - unifi

    - import_role: name=../roles/k3s/authentik
      tags:
        - authentik
        
    - import_role: name=../roles/k3s/qbittorrent
      tags:
        - qbittorrent

    - import_role: name=../roles/k3s/netboot
      tags:
        - netboot
        - pxe

    - import_role: name=../roles/k3s/heimdall
      tags:
        - heimdall
        - homepage

    - import_role: name=../roles/k3s/snipe-it
      tags:
        - snipe-it
        - snipe

    - import_role: name=../roles/k3s/dhcp
      tags:
        - dhcp
    
    # TODO: NextCloud
    # TODO: Plex

    # TODO: Radius for VPN (?)


  # - import_role: name=../roles/k3s/dashboard
  #   tags:
  #     - dashboard
  # TODO: Ingress through traefik at k8s.<domain>
  # TODO: Authentication
  # TODO: Switch for standard K8S dashboard
  # TODO: Pass token as header so it doesn't have be entered through UI