---
- name: "Install rkhunter (to detect rootkits)"
  hosts: all
  become: true
  become_method: sudo
  tasks:
  - name: Install rkhunter
    package:
      name: rkhunter
      state: present

  - name: Disable web_cmd
    lineinfile:
      path: /etc/rkhunter.conf
      line: "WEB_CMD=\"/bin/false\""
      state: absent

  - name: Set UPDATE_MIRRORS
    lineinfile:
      path: /etc/rkhunter.conf
      regexp: "UPDATE_MIRRORS=.*"
      line: "UPDATE_MIRRORS=1"
      state: present

  - name: Set MIRRORS_MODE
    lineinfile:
      path: /etc/rkhunter.conf
      regexp: "MIRRORS_MODE=.*"
      line: "MIRRORS_MODE=0"
      state: present
    
  - name: Set whether root ssh access is supposed to be allowed
    lineinfile:
      path: /etc/rkhunter.conf
      regexp: "ALLOW_SSH_ROOT_USER=.*"
      line: "ALLOW_SSH_ROOT_USER={{ ssh_permit_root_login }}"
      state: present

  - name: Disable test for promisc interfaces
    lineinfile:
      path: /etc/rkhunter.conf
      regexp: "DISABLE_TESTS =.*"
      line: "DISABLE_TESTS=promisc"
      state: present