---
- name: "Proxmox Virtual Environment Configuration"
  hosts: proxmox_nodes
  become: true
  become_method: sudo
  tasks:
    - name: "Use pve apt repository which does not require subscription"
      import_role: 
        name: "./roles/utils/pve-apt-repository"

    # Is chrony enabled by default ???
    - name: "Set up ntp/chrony"
      tags:
        - chrony
      import_role:
        name: oasis_roles.system.chrony

    - name: "Force chrony to sync time immediately"
      tags:
        - chrony
      command: chronyc makestep
    # ?????

    - name: "Install sudo"
      package:
        name: sudo
        state: present

    - name: "Create local non-root ssh user"
      tags:
        - ssh
      include_role:
        name: "./roles/utils/ssh-user"
      vars:
        user_name: "{{ admin_user }}"

    - name: "SSH hardening"
      import_role:
        name: geerlingguy.security
      tags:
        - ssh
      vars:
        security_ssh_password_authentication: "no"
        security_ssh_permit_root_login: "no"
        security_ssh_usedns: "no"
        security_ssh_permit_empty_password: "no"
        security_ssh_challenge_response_auth: "no"
        security_ssh_gss_api_authentication: "no"
        security_ssh_x11_forwarding: "no"
        security_sudoers_passwordless:
        - "{{ admin_user }}"

    - name: "Install Lynis"
      tags:
        - lynis
      include_role:
        name: "./roles/utils/lynis"

    # TODO: Configure glusterfs cluster