---
- name: "Proxmox Virtual Environment Configuration"
  hosts: proxmox_nodes
  become: true
  become_method: sudo
  tasks:
    - name: Remove enteprise repository
      ansible.builtin.file:
        path: /etc/apt/sources.list.d/pve-enterprise.list
        state: absent

    - name: Add free (no-subscription) repository
      register: add_nosub
      copy:
        dest: /etc/apt/sources.list.d/pve-no-subscription.list
        content: |
          deb http://download.proxmox.com/debian/pve buster pve-no-subscription

    - name: Update apt sources
      ansible.builtin.apt:
        update_cache: yes
      when: add_nosub.changed

    - name: "Install sudo"
      package:
        name: sudo
        state: present

    - name: "Set up port redirect (443 -> 8006)"
      tags:
        - proxmox_ui_port
      ansible.builtin.iptables:
        table: nat
        chain: PREROUTING
        protocol: tcp
        destination_port: 443
        to_ports: 8006
        jump: REDIRECT
        comment: "Enable Proxmox admin interface on 443"