---
- name: "Proxmox Virtual Environment Configuration"
  hosts: proxmox_nodes
  become: true
  become_method: sudo
  tasks:
    - name: "Use pve apt repository which does not require subscription"
      import_role: 
        name: "./roles/utils/pve-apt-repository"

    - name: "Install sudo"
      package:
        name: sudo
        state: present

    - import_tasks: ./shared/chrony.yml
    - import_tasks: ./shared/ssh.yml

    - name: "Install Lynis"
      tags:
        - lynis
      import_role:
        name: "./roles/utils/lynis"

    - name: "Set up port redirect (443 -> 8006)"
      tags:
        - proxmox_ui_port
      ansible.builtin.iptables:
        table: nat
        chain: PREROUTING
        protocol: tcp
        destination_port: 443
        to_ports: 8006
        jump: REDIRECT
        comment: "Enable Proxmox admin interface on 443"


    # TODO: Configure glusterfs cluster