---
- name: "SMTP Relay set up"
  hosts: smtp_relays
  become: true
  become_method: sudo
  tasks:
  
  - name: "Execute opensmtpd-relay role"
    import_role:
      name: "../roles/opensmtpd-relay"
    vars:
      opensmtpd_relay_dir: "{{ services_root_dir }}/opensmtpd-relay"