---
- name: "Configure ssh client"
  hosts: localhost
  connection: local
  tasks:
  - name: Make sure StormSSH module is installed (required for the ssh_config module below)
    pip:
      name: stormssh

  - name: Add a host in the configuration
    community.general.ssh_config:
      user: "{{ admin_user }}"
      host: "{{ item }}"
      hostname: "{{ hostvars[item].fqdn }}"
      forward_agent: yes # To enable YubiKey forwarding
      state: present
    with_items: "{{ groups['all'] }}"