---
- name: "SSH hardening & basic set up"
  hosts: "{{ hostlist | default('all') }}" # To allow calling this playbook from other playbooks on a specified set of hosts
  become: true
  become_method: sudo
  tasks:
  - name: "SSH hardening"
    import_role:
      name: geerlingguy.security
    vars:
      security_ssh_password_authentication: "no"
      security_ssh_permit_root_login: "{{ ssh_permit_root_login }}"
      security_ssh_usedns: "no"
      security_ssh_permit_empty_password: "no"
      security_ssh_challenge_response_auth: "no"
      security_ssh_gss_api_authentication: "no"
      security_ssh_x11_forwarding: "no"
      security_sudoers_passwordless:
      - "{{ admin_user }}"