---
- name: "Homecentr services running in the Docker Swarm Cluster"
  hosts: swarm_nodes
  become: true
  become_method: sudo
  tasks:
  - name: "Create local Docker macvlan network on all nodes"
    docker_network:
      name: "{{ docker_macvlan_network }}"
      driver: macvlan
      driver_options:
        parent: "{{ docker_macvlan_interface }}"
      ipam_config:
        - subnet: "{{ docker_macvlan_subnet }}"
          gateway: "{{ docker_macvlan_gateway }}"
          iprange: "{{ docker_macvlan_iprange }}"

  - name: "Swarm Local Network Connector"
    tags:
      - network-connector
    import_role:
      name: "./roles/services/network-connector"

  - name: "Certbot (SSL certificates provider)"
    tags:
      - certbot
    import_role:
      name: "./roles/services/certbot"
    vars:
      certbot_root_dir: "{{ homecentr_root }}/certbot"
      certbot_certificate_domain: "*.{{ homecentr_root_domain }}"
      certbot_cert_readers_group_id: 9103
      certbot_acme_email: "{{ secret_acme_email }}"
      certbot_cloudflare_api_token: "{{ secret_cloudflare_api_token }}"

  - name: "HTTP/HTTPS Ingress"
    tags:
      - ingress
    import_role:
      name: "./roles/services/ingress"
    vars:
      ingress_certificates_group_id: 9103
      ingress_certificates_dir: "{{ homecentr_root }}/certbot/certs"
      ingress_root_dir: "{{ homecentr_root }}/ingress"
      ingress_dashboard_domain: "ingress.{{ homecentr_root_domain }}"

  - name: "Auth"
    tags:
      - auth
    import_role:
      name: "./roles/services/auth"
    vars:
      auth_root_dir: "{{ homecentr_root }}/auth"
      auth_domain: "auth.{{ homecentr_root_domain }}"
      auth_oidc_url: "https://login.microsoftonline.com/{{ azure_ad_tenant_id }}/v2.0"

  - name: "Portainer"
    tags:
      - portainer
    import_role:
      name: "./roles/services/portainer"
    vars:
      portainer_root_dir: "{{ homecentr_root }}/portainer"
      portainer_domain: "portainer.{{ homecentr_root_domain }}"
      portainer_agent_secret: "{{ secret_portainer_agent_secret }}"
      portainer_admin_password: "{{ secret_portainer_admin_password }}"
      portainer_oidc_url: "https://login.microsoftonline.com/{{ azure_ad_tenant_id }}/v2.0"
      portainer_oidc_client_id: "{{ secret_portainer_oauth_client_id }}"
      portainer_oidc_client_secret: "{{ secret_portainer_oauth_client_secret }}"
      portainer_admin_users:
        - l.holota@outlook.com

  # - name: "DNS"
  #   tags:
  #     - dns
  #   import_role:
  #     name: "./roles/services/dns"
  #   vars:
  #     dns_publish_network: "{{ docker_macvlan_network }}"
  #     dns_master_ipv4: "10.1.2.64"
  #     dns_slave_ipv4: "10.1.2.65"
  #     dns_master_slave_secret: "Passw0rd123456" # TODO: Move this to vault encrypted file
  #     dns_forward_zone_domain: "homecentr.io"
  #     dns_services_reverse_zone_range: "2.1.10"