---
- name: "Docker Swarm Cluster Nodes Configuration"
  hosts: swarm_nodes
  become: true
  become_method: sudo
  tasks:
    - name: "Set up ntp/chrony"
      include_role:
        name: oasis_roles.system.chrony

    - name: "Force chrony to sync time immediately"
      command: chronyc makestep

    - name: "Create local non-root ssh user"
      import_role:
        name: "./roles/utils/ssh-user"
      vars:
        user_name: "{{ admin_user }}"

    - name: "Enable EPEL repository" # Required to install fail2ban
      yum:
        name: epel-release
        state: latest

    - name: "SSH hardening"
      import_role:
        name: geerlingguy.security
      vars:
        security_ssh_password_authentication: "no"
        security_ssh_permit_root_login: "yes"
        security_ssh_usedns: "no"
        security_ssh_permit_empty_password: "no"
        security_ssh_challenge_response_auth: "no"
        security_ssh_gss_api_authentication: "no"
        security_ssh_x11_forwarding: "no"
        security_sudoers_passwordless:
        - "{{ admin_user }}"

    - name: "Install Lynis"
      import_role:
        name: "./roles/utils/lynis"

    # Workaround: Docker dependencies conflict with podman's dependencies which are installed by default with CentOS
    - name: "Uninstall packages conflicting with Docker on CentOS 8"
      yum:
        name:
          - podman
          - buildah
        state: absent

    - name: "Install Docker"
      include_role:
        name: "geerlingguy.docker"
      vars:
        docker_edition: 'ce'
        docker_install_compose: true
        docker_service_state: started
        docker_users:
          - "{{ admin_user }}"

    - name: "Unify Docker group GID across the cluster"
      group:
        gid: "{{ docker_gid }}"
        name: "docker"

    - name: "Install Docker pip module"
      include_role:
        name: geerlingguy.pip
      vars:
        pip_package: python3-pip
        pip_install_packages:
        - name: docker
        - name: jsondiff
        - name: pyyaml

    - name: "Set up Docker Swarm"
      tags:
      - swarm
      import_role:
        name: "./roles/utils/docker-swarm-cluster"