---
- name: "Test"
  hosts: localhost
  vars:
    # portainer_oidc_url: "https://cimpress.auth0.com"
    portainer_oidc_url: "https://login.microsoftonline.com/53174009-29d5-4c20-8bd0-0e2b2b0de6a8/v2.0"
    portainer_domain: portainer.test.io
  tasks:
    - name: Fetch discovery document
      ansible.builtin.uri:
        url: "{{ portainer_oidc_url }}/.well-known/openid-configuration"
        method: GET
        return_content: yes
      register: portainer_oidc_discovery
    
    - name: Dump output
      debug:
        var: portainer_oidc_discovery
    
    - name: Get field
      debug:
        msg: "{{ (portainer_oidc_discovery.content | from_json).end_session_endpoint ~ '?post_logout_redirect_uri=' ~ (('https://' ~ portainer_domain) | urlencode) if (portainer_oidc_discovery.content | from_json).end_session_endpoint is defined else '' }}"