---
- name: "Manage non-root admin user"
  hosts: all
  become: true
  become_method: sudo
  tasks:
  - name: "Create user {{ admin_user | mandatory }}"
    ansible.builtin.user:
      password: "{{ secret_admin_user_password | mandatory | password_hash('sha512', secret_admin_user_password_salt) }}"
      name: "{{ admin_user | mandatory }}"
      shell: /bin/bash
      state: present

  - name: "Download public keys from GitHub"
    uri:
      url: "https://github.com/{{ admin_user_github_name | default(admin_user) }}.keys"
      return_content: yes
    register: public_keys

  - name: Set authorized key
    authorized_key:
      user: "{{ admin_user | mandatory }}"
      state: present
      key: "{{ public_keys['content'] }}"

- name: "Manage root user"
  hosts: all
  become: true
  become_method: sudo
  tasks:
    - name: "Set root user's password"
      ansible.builtin.user:
        name: root
        password: "{{ secret_root_user_password | mandatory | password_hash('sha512', secret_root_user_password_salt) }}"
