---
- name: "Validate variables"
  fail:
    msg: "Required variable {{item}} has not been provided"
  when: vars[item] is undefined
  loop:
    - certbot_docker_image_version
    - certbot_group_id
    - certbot_group_name
    - certbot_user_id
    - certbot_user_name
    - certbot_use_staging
    - certbot_cert_readers_group_name
    - certbot_cert_readers_group_id
    - certbot_root_dir
    - certbot_acme_email
    - certbot_cloudflare_api_token
    - certbot_certificate_domain

- import_tasks: ./iam.yml

- import_tasks: ./dirs.yml
  run_once: true

- name: "Create cloudflare credential file"
  run_once: true
  template:
    src: cloudflare.ini.j2
    dest: "{{ certbot_root_dir }}/secrets/cloudflare.ini"
    owner: "{{ certbot_user_id | string }}"
    group: "{{ certbot_group_id | string }}"
    mode: '0600'

# Create Docker stack
- name: "Certbot Docker stack"
  run_once: true
  docker_stack:
    prune: yes
    name: homecentr-certbot
    compose:
      - "{{ lookup('template', 'docker-compose.yml.j2') | from_yaml }}"

# Wait for the certificate to be issued so that other services can immediately use it
- name: "Wait for certificates to be issued"
  with_items:
    - fullchain.pem
    - cert.pem
    - privkey.pem
  wait_for:
    path: "{{ certbot_root_dir }}/certs/{{ item }}"
    state: present
    timeout: 120