- name: Add host entries for other glusterfs nodes (with and without domain)
  lineinfile:
    path: /etc/hosts
    regexp: "^{{ hostvars[item].gluster_ip | replace('.', '\\.') }}\\W+{{ hostvars[item].gluster_hostname | replace('.', '\\.') }}\\W+{{ hostvars[item].gluster_fqdn | mandatory | replace('.', '\\.') }}\\W*$"
    line: "{{ hostvars[item].gluster_ip }} {{ hostvars[item].gluster_hostname }} {{ hostvars[item].gluster_fqdn }}"
  with_items: "{{ play_hosts }}"